import type { Metadata } from "next";
import { Toaster } from "sonner";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "SHOP.CO",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <Toaster position="top-center" />
       {children}
      </body>
    </html>
  );
}
