import type { Metadata } from "next";
import "./globals.css";
import TopHeader from "./Components/TopHeader";
import Navbar from "./Components/Navbar";
import { Toaster } from "sonner";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`{inter.className} bg-white `}
      >
            <Toaster position="top-center" />
          {children}
      
          <TopHeader />
          <Navbar />
      </body>
    </html>
  );
}
