import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopHeader from "./Components/TopHeader";
import Navbar from "./Components/Navbar";
import { CartProvider } from "./context/CartContext";
import Footer from "./Components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`{inter.className} md:max-w-[1440px] md:w-[1440px] max-w-[390px] mx-auto   relative `}
      >
        <CartProvider>
          {children}
          <TopHeader />
          <Navbar />
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
