import type { Metadata } from "next";
import "./globals.css";
import TopHeader from "./Components/TopHeader";
import Navbar from "./Components/Navbar";
import { Toaster } from "sonner";
import { Inter } from "next/font/google";
// import SessionProviderWrapper from "./Components/SessionProviderWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <Toaster position="top-center" />
        <TopHeader />
        <Navbar />
        {/* Wrap children in SessionProviderWrapper */}
       {children}
      </body>
    </html>
  );
}
